with System;
package H01 is
   type Int_Access is access all Integer;
   type Rec is record
      A : Integer := 1;
      B : Integer := 1;
   end record;
   type Arr is array (1 .. 4) of Integer;
   G : Integer := 5;
   V : Integer := 5 with Volatile;
   Shared : aliased Integer := 5;
   Shared_Ptr : Int_Access := Shared'Access;
   procedure Zero_G;
   function Zero_G_Fn return Integer;
   procedure Clear (X : in out Integer);
   procedure Clear_Rec (X : in out Rec);
   procedure Set_Through (P : Int_Access);
   procedure Ext (X : in out Integer) with Import, Convention => C, External_Name => "ext";
   procedure Ext_No_Args with Import, Convention => C, External_Name => "ext0";
   function Ext_Fn return Integer with Import, Convention => C, External_Name => "extf";
   procedure P_Rename (N : Integer; Sink : out Integer);
   procedure P_Overlay (N : Integer; Sink : out Integer);
   procedure P_Global_Proc (N : Integer; Sink : out Integer);
   procedure P_Global_Fn (N : Integer; Sink : out Integer);
   procedure P_Global_Fn_Cond (N : Integer; Sink : out Integer);
   procedure P_In_Out (N : Integer; Sink : out Integer);
   procedure P_Rec_Assign (N : Integer; Sink : out Integer);
   procedure P_Rec_Call (N : Integer; Sink : out Integer);
   procedure P_Rec_Comp_Call (N : Integer; Sink : out Integer);
   procedure P_Arr_Dyn (N : Integer; Sink : out Integer);
   procedure P_Arr_Agg (N : Integer; Sink : out Integer);
   procedure P_Arr_Call (N : Integer; Sink : out Integer);
   procedure P_Nested (N : Integer; Sink : out Integer);
   procedure P_Nested_Fn (N : Integer; Sink : out Integer);
   procedure P_Volatile (N : Integer; Sink : out Integer);
   procedure P_Aliased_Global (N : Integer; Sink : out Integer);
   procedure P_Access_Attr (N : Integer; Sink : out Integer);
   procedure P_Import (N : Integer; Sink : out Integer);
   procedure P_Import_Global (N : Integer; Sink : out Integer);
   procedure P_Import_Fn (N : Integer; Sink : out Integer);
   procedure P_Out_Alias (A : out Integer; B : in out Integer);
   procedure P_Rec_Whole_In_Out (R : in out Rec; Sink : out Integer);
   procedure P_Nested_Rec (N : Integer; Sink : out Integer);
   procedure P_Slice (N : Integer; Sink : out Integer);
   procedure P_Loop_Arr (N : Integer; Sink : out Integer);
end H01;
