package H02 is
   subtype Small is Integer range 0 .. 10;
   Failed : exception;
   procedure Might_Raise (V : Integer);
   procedure F01 (N : Integer; Sink : out Integer);
   procedure F02 (N : Integer; Sink : out Integer);
   procedure F03 (N : Integer; Sink : out Integer);
   procedure F04 (N : Integer; Sink : out Integer);
   procedure F05 (N : Integer; Sink : out Integer);
   procedure F06 (N : Integer; M : Integer; Sink : out Integer);
   procedure F07 (N : Integer; Sink : out Integer);
   procedure F08 (N : Integer; M : Integer; Sink : out Integer);
   procedure F09 (N : Integer; M : Integer; Sink : out Integer);
   procedure F10 (N : Integer; Sink : out Integer);
   procedure F11 (N : Integer; Sink : out Integer);
   procedure F12 (N : Integer; Sink : out Integer);
   procedure F13 (N : Integer; Sink : out Integer);
   procedure F14 (N : Integer; Sink : out Integer);
   procedure F15 (N : Integer; Sink : out Integer);
   procedure F16 (N : Integer; Sink : out Integer);
   procedure F17 (N : Integer; Sink : out Integer);
   procedure F18 (N : Integer; Sink : out Integer);
   procedure F19 (N : Integer; Sink : out Integer);
   procedure F20 (N : Integer; Sink : out Integer);
   procedure F21 (N : Integer; Sink : out Integer);
   procedure F22 (N : Integer; Sink : out Integer);
   procedure F23 (N : Integer; Sink : out Integer);
   procedure F24 (N : Integer; Sink : out Integer);
   procedure F25 (N : Integer; Sink : out Integer);
   function F26 (N : Integer) return Small;
   function F27 (N : Integer) return Integer;
   procedure F28 (N : Integer; Sink : out Integer);
   procedure F29 (N : Integer; Sink : out Integer);
   procedure F30 (N : Integer; Sink : out Integer);
end H02;
