with System;
package H09 is
   type Vol_Int is new Integer with Volatile;
   type Arr is array (1 .. 4) of Integer;
   type Money is new Integer;
   G : Integer := 5;
   Alias_G : Integer renames G;
   Over_G : Integer;
   for Over_G'Address use G'Address;
   pragma Import (Ada, Over_G);
   P_Vol : Integer := 5;
   pragma Volatile (P_Vol);
   P_Atom : Integer := 5;
   pragma Atomic (P_Atom);
   T_Vol : Vol_Int := 5;
   Imported : Integer;
   pragma Import (C, Imported, "imported_thing");
   function Reset return Integer;
   function Reset_With (X : Integer := Reset) return Integer;
   function Reset_Out (X : out Integer) return Integer;
   function "+" (L, R : Money) return Money;
   function Renamed_Reset return Integer renames Reset;
   generic
   function Gen_Reset return Integer;
   function Inst_Reset is new Gen_Reset;
   procedure U01 (N : Integer; Sink : out Integer);
   procedure U02 (N : Integer; Sink : out Integer);
   procedure U03 (N : Integer; Sink : out Integer);
   procedure U04 (N : Integer; Sink : out Integer);
   procedure U05 (N : Integer; Sink : out Integer);
   procedure U06 (N : Integer; Sink : out Integer);
   procedure U07 (N : Integer; Sink : out Integer);
   procedure U08 (N : Integer; Sink : out Integer);
   procedure U09 (N : Integer; Sink : out Integer);
   procedure U10 (N : Integer; Sink : out Integer);
   procedure U11 (N : Integer; Sink : out Integer);
   procedure U12 (N : Integer; Sink : out Integer);
   procedure U13 (N : Integer; Sink : out Integer);
   procedure U14 (N : Integer; Sink : out Integer);
   procedure U15 (N : Integer; Sink : out Integer);
   procedure U16 (N : Integer; Sink : out Integer);
   function U17 (N : Integer) return Integer;
   procedure U18 (N : Integer; Sink : out Integer);
   procedure U19 (P : in out Integer; Sink : out Integer);
   procedure U20 (N : Integer; Sink : out Integer);
end H09;
